### ISSUE TITLE
week 4

### ISSUE THREAD

**Issue by sw-cho** [sw-cho/assignment#1]
### mario pod 배포
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  labels:
    app: mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
        ports:
        - containerPort: 8080
          name: http

---

apiVersion: v1
kind: Service
metadata:
  name: mario
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: mario
  type: NodePort
```

### 파드 및 서비스 객체 확인
![image](https://user-images.githubusercontent.com/66065293/153714443-c970f33b-9916-4910-bb8d-e1569ea7f5bb.png)

### curl 확인 
`svc.externalTrafficPolicy=Cluster` 이기 때문에 master 노드 IP 를 사용해도 접속 가능
단, 클라이언트 IP 가 노드 IP 로 SNAT 된다. 외부 클라이언트 IP 를 알 수 없다.
![image](https://user-images.githubusercontent.com/66065293/153714470-408c1166-2287-494c-9491-3393e2ee9d27.png)

외부 클라이언트 IP 를 보존하기 위해서 `svc.externalTrafficPolicy=Local` 로 변경했다. 파드가 떠있지 않는 노드인 master 노드 IP 로는 접속이 불가능하다. 

![image](https://user-images.githubusercontent.com/66065293/153714496-f765f5d4-930e-4cd5-8af1-d4418c74e953.png)

![image](https://user-images.githubusercontent.com/66065293/153714511-7eb49f0d-7a30-4018-bc78-c3a335ee558f.png)
